
INSERT INTO TB_CATEGORIA(nome, tipo) VALUES('BELEZA', 'teste01');
INSERT INTO TB_CATEGORIA(nome, tipo) VALUES('HIGIENE', 'teste001');

INSERT INTO TB_PRODUTO(nome, descricao, preco, data_Cadastro, categoria_id) VALUES('POMADA CAPILAR', 'teste001', 10,'2021-10-29',1);
INSERT INTO TB_PRODUTO(nome, descricao, preco, data_Cadastro, categoria_id) VALUES('ESCOVA DE DENTE', 'teste00', 10,'2021-10-29',1);

INSERT INTO TB_CLIENTE(nome, cpf) VALUES('JOSE', '12343212343');
INSERT INTO TB_CLIENTE(nome, cpf) VALUES('ADRIANO', '12343212344');

INSERT INTO TB_PEDIDO(EMAIL, DATA_DE_CRIACAO, STATUS, VALOR_TOTAL, itens_id, cliente_id) VALUES('dre@dre.com.br', '2021-10-29','AGUARDANDO_CONFIRMACAO', 10 ,1 ,1);
INSERT INTO TB_PEDIDO(EMAIL, DATA_DE_CRIACAO, STATUS, VALOR_TOTAL, itens_id, cliente_id) VALUES('PRI@dre.com.br', '2021-10-29','AGUARDANDO_CONFIRMACAO', 10 ,2 ,2);

INSERT INTO TB_ITEM(NOME, VALOR_UNITARIO, pedido_Id, produto_id) VALUES('POMADA CAPILAR', 10, 1, 1);
INSERT INTO TB_ITEM(NOME, VALOR_UNITARIO, pedido_Id, produto_id) VALUES('ESCOVA DE DENTE', 10, 2, 2);